// generated by Textmapper; DO NOT EDIT

package collision

const tmNumClasses = 5

var tmRuneClass = []uint8{
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1, 2,
}

const tmRuneClassLen = 104
const tmFirstRule = -1

var tmStateMap = []int{
	0,
}

var tmLexerAction = []int8{
	-1, -2, 3, -2, 1, -2, 1, 1, 1, 2, -4, -4, -4, -4, -4, -2,
	-2, -2, 4, -2, -3, -3, -3, -3, -3,
}
