// generated by Textmapper; DO NOT EDIT

package collision

import (
	"fmt"
)

// Symbol represents a set of all terminal and non-terminal symbols of the collision language.
type Symbol int

var symbolStr = [...]string{
	"input",
	"FuncHeader",
	"GC",
	"GCopt",
}

func (n Symbol) String() string {
	if n < Symbol(NumTokens) {
		return Token(n).String()
	}
	i := int(n) - int(NumTokens)
	if i < len(symbolStr) {
		return symbolStr[i]
	}
	return fmt.Sprintf("nonterminal(%d)", n)
}

var tmAction = []int32{
	-3, -1, 0, 3, 1, 2, -1, -2,
}

var tmLalr = []int32{
	2, -1, 0, 4, -1, -2,
}

var tmGoto = []int32{
	0, 2, 2, 4, 6, 8, 10, 12, 14,
}

var tmFromTo = []int8{
	6, 7, 0, 1, 1, 5, 0, 6, 0, 2, 0, 3, 0, 4,
}

var tmRuleLen = []int8{
	1, 1, 2, 1, 0,
}

var tmRuleSymbol = []int32{
	4, 5, 6, 7, 7,
}
