// generated by Textmapper; DO NOT EDIT

package collision

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the collision language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota - 1
	EOI

	INVALID_TOKEN
	GC // gc
	STRING_LIT

	NumTokens
)

var tokenStr = [...]string{
	"EOI",

	"INVALID_TOKEN",
	"gc",
	"STRING_LIT",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
