// generated by Textmapper; DO NOT EDIT

package selector

import (
	"github.com/mewspring/foo/collision"
)

type Selector func(nt collision.NodeType) bool

var (
	Any        = func(t collision.NodeType) bool { return true }
	FuncHeader = func(t collision.NodeType) bool { return t == collision.FuncHeader }
	GC         = func(t collision.NodeType) bool { return t == collision.GC }
)

func OneOf(types ...collision.NodeType) Selector {
	if len(types) == 0 {
		return func(collision.NodeType) bool { return false }
	}
	const bits = 32
	max := 1
	for _, t := range types {
		if int(t) > max {
			max = int(t)
		}
	}
	size := (max + bits) / bits
	bitarr := make([]uint32, size)
	for _, t := range types {
		bitarr[uint(t)/bits] |= 1 << (uint(t) % bits)
	}
	return func(t collision.NodeType) bool {
		i := uint(t) / bits
		return int(i) < len(bitarr) && bitarr[i]&(1<<(uint(t)%bits)) != 0
	}
}
