// generated by Textmapper; DO NOT EDIT

package issue24

import (
	"fmt"
)

type NodeType int

type Listener func(t NodeType, offset, endoffset int)

const (
	NoType NodeType = iota
	Foo  // Src=ID Indices=(ID)*
	ID
	NodeTypeMax
)

var nodeTypeStr = [...]string{
	"NONE",
	"Foo",
	"ID",
}

func (t NodeType) String() string {
	if t >= 0 && int(t) < len(nodeTypeStr) {
		return nodeTypeStr[t]
	}
	return fmt.Sprintf("node(%d)", t)
}

var ruleNodeType = [...]NodeType{
	Foo, // Foo : 'gep' ID list_of_','_and_1_elements
	0, // list_of_','_and_1_elements : list_of_','_and_1_elements ',' ID
	0, // list_of_','_and_1_elements :
	ID, // ID : id_tok
}

