// generated by Textmapper; DO NOT EDIT

package issue24

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the issue24 language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota-1
	EOI

	INVALID_TOKEN
	ID_TOK
	GEP // gep
	COMMA // ,
	WHITESPACE

	NumTokens
)

var tokenStr = [...]string{
	"EOI",

	"INVALID_TOKEN",
	"ID_TOK",
	"gep",
	",",
	"WHITESPACE",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
