// generated by Textmapper; DO NOT EDIT

package ast

import (
	"github.com/mewspring/foo/collision"
	"log"
)

func ToCollisionNode(n Node) CollisionNode {
	if n == nil {
		return nil
	}
	switch n.Type() {
	case collision.FuncHeader:
		return &FuncHeader{n}
	case collision.GC:
		return &GC{n}
	}
	log.Fatalf("unknown node type %v\n", n.Type())
	return nil
}
