// generated by Textmapper; DO NOT EDIT

package baz

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the baz language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota-1
	EOI

	INVALID_TOKEN
	COMMENT
	WHITESPACE
	LOCAL_IDENT_TOK
	INT_LIT_TOK
	INT_TYPE_TOK
	METADATA // metadata
	OPAQUE // opaque
	TYPE // type
	VOID // void
	CHAR_X // x
	LBRACK
	RBRACK
	ASSIGN

	NumTokens
)

var tokenStr = [...]string{
	"EOI",

	"INVALID_TOKEN",
	"COMMENT",
	"WHITESPACE",
	"LOCAL_IDENT_TOK",
	"INT_LIT_TOK",
	"INT_TYPE_TOK",
	"metadata",
	"opaque",
	"type",
	"void",
	"x",
	"LBRACK",
	"RBRACK",
	"ASSIGN",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
