// generated by Textmapper; DO NOT EDIT

package ast

import (
	"github.com/mewspring/foo/issue25/selector"
)

// Interfaces.

type Issue25Node interface {
	Issue25Node() *Node
}

// All types implement Issue25Node.
func (n Foo) Issue25Node() *Node { return n.Node }
func (n ID) Issue25Node() *Node { return n.Node }

// Types.

type Foo struct {
	*Node
}

func (n Foo) Bars() []ID {
	nodes := n.Children(selector.ID)
	var ret = make([]ID, 0, len(nodes))
	for _, node := range nodes {
		ret = append(ret, ID{node})
	}
	return ret
}

func (n Foo) Bar() ID {
	return ID{n.Children(selector.ID).Next(selector.ID)}
}

type ID struct {
	*Node
}


