// generated by Textmapper; DO NOT EDIT

package selector

import (
	"github.com/mewspring/foo/issue25"
)

type Selector func (nt issue25.NodeType) bool

var (
	Any = func(t issue25.NodeType) bool { return true }
	Foo = func(t issue25.NodeType) bool { return t == issue25.Foo }
	ID = func(t issue25.NodeType) bool { return t == issue25.ID }
)

func OneOf(types ...issue25.NodeType) Selector {
	if len(types) == 0 {
		return func(issue25.NodeType) bool { return false }
	}
	const bits = 32
	max := 1
	for _, t := range types {
		if int(t) > max {
			max = int(t)
		}
	}
	size := (max + bits) / bits
	bitarr := make([]uint32, size)
	for _, t := range types {
		bitarr[uint(t)/bits] |= 1 << (uint(t) % bits)
	}
	return func(t issue25.NodeType) bool {
		i := uint(t)/bits
		return int(i) < len(bitarr) && bitarr[i]&(1<<(uint(t)%bits)) != 0
	}
}
