// generated by Textmapper; DO NOT EDIT

package fob

import (
	"fmt"
)

// Symbol represents a set of all terminal and non-terminal symbols of the fob language.
type Symbol int

var symbolStr = [...]string{
	"input",
	"FuncHeader",
	"CallingConv",
	"CallingConvopt",
}

func (n Symbol) String() string {
	if n < Symbol(NumTokens) {
		return Token(n).String()
	}
	i := int(n) - int(NumTokens)
	if i < len(symbolStr) {
		return symbolStr[i]
	}
	return fmt.Sprintf("nonterminal(%d)", n)
}

var tmAction = []int32{
	-3, 2, 3, 4, 0, 5, 1, -1, -2,
}

var tmLalr = []int32{
	2, -1, 3, -1, 4, -1, 0, 6, -1, -2,
}

var tmGoto = []int32{
	0, 2, 2, 4, 6, 8, 10, 12, 14, 16,
}

var tmFromTo = []int8{
	7, 8, 0, 1, 0, 2, 0, 3, 0, 7, 0, 4, 0, 5, 0, 6,
}

var tmRuleLen = []int8{
	1, 1, 1, 1, 1, 1, 0,
}

var tmRuleSymbol = []int32{
	5, 6, 7, 7, 7, 8, 8,
}
