// generated by Textmapper; DO NOT EDIT

package fob

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the fob language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota - 1
	EOI

	INVALID_TOKEN
	X86_FASTCALLCC // x86_fastcallcc
	X86_STDCALLCC  // x86_stdcallcc
	X86_THISCALLCC // x86_thiscallcc

	NumTokens
)

var tokenStr = [...]string{
	"EOI",

	"INVALID_TOKEN",
	"x86_fastcallcc",
	"x86_stdcallcc",
	"x86_thiscallcc",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
