// generated by Textmapper; DO NOT EDIT

package ast

import (
	"github.com/mewspring/foo/baz"
	"log"
)

func ToBazNode(n Node) BazNode {
	if n == nil {
		return nil
	}
	switch n.Type() {
	case baz.ArrayType:
		return &ArrayType{n}
	case baz.IntType:
		return &IntType{n}
	case baz.LocalIdent:
		return &LocalIdent{n}
	case baz.MetadataType:
		return &MetadataType{n}
	case baz.Module:
		return &Module{n}
	case baz.OpaqueType:
		return &OpaqueType{n}
	case baz.TypeDef:
		return &TypeDef{n}
	case baz.UintLit:
		return &UintLit{n}
	case baz.VoidType:
		return &VoidType{n}
	}
	log.Fatalf("unknown node type %v\n", n.Type())
	return nil
}
