// generated by Textmapper; DO NOT EDIT

package qux

import (
	"fmt"
)

// Symbol represents a set of all terminal and non-terminal symbols of the qux language.
type Symbol int

var symbolStr = [...]string{
	"input",
	"Foo",
	"Bar",
}

func (n Symbol) String() string {
	if n < Symbol(NumTokens) {
		return Token(n).String()
	}
	i := int(n) - int(NumTokens)
	if i < len(symbolStr) {
		return symbolStr[i]
	}
	return fmt.Sprintf("nonterminal(%d)", n)
}

var tmAction = []int32{
	-1, 1, 0, -1, -2,
}

var tmGoto = []int32{
	0, 2, 2, 4, 4, 6, 8, 8,
}

var tmFromTo = []int8{
	3, 4, 0, 1, 0, 3, 0, 2,
}

var tmRuleLen = []int8{
	1, 1, 1,
}

var tmRuleSymbol = []int32{
	4, 5, 6,
}
