// generated by Textmapper; DO NOT EDIT

package ast

import (
	"fmt"
	"github.com/mewspring/foo/issue24"
)

func ToIssue24Node(n *Node) Issue24Node {
	switch n.Type() {
	case issue24.Foo:
		return &Foo{n}
	case issue24.ID:
		return &ID{n}
	}
	panic(fmt.Errorf("ast: unknown node type %v", n.Type()))
	return nil
}
